#!/usr/bin/python3

import sys
import threading
import time
import numpy as np
import matplotlib.pyplot as plt
import functions

class ImageView():
    def __init__(self, shape):
        self.shape = shape
        self.buf_size = np.prod(shape)

    def run(self):
        img = self.load_image()
        if img is None:
            return

        self.aximg = plt.imshow(img, vmin=0.0, vmax=255.0, cmap="gray")
        self.aximg.figure.canvas.draw()

        thread = threading.Thread(target = self.update_thread)
        thread.daemon = True
        thread.start()
        try:
            plt.show()
        except KeyboardInterrupt:
            pass

    def update_thread(self):
        i = 1
        while True:
            img = self.load_image()
            if img is None:
                return

            try:
                self.aximg.set_data(img)
                self.aximg.figure.canvas.draw()
            except:
                return

    def load_image(self):
        buf = sys.stdin.buffer.read(self.buf_size)
        if len(buf) < self.buf_size:
            return None

        img = np.frombuffer(buf, dtype="uint8")
        return img.reshape(self.shape)

if __name__ == "__main__":

    if len(sys.argv) < 2:
        sys.stderr.write("\nUsage:\n\n");
        sys.stderr.write("\timage_show H,W\n")
        sys.stderr.write("\timage_show H,W,3\n\n")
        sys.exit(1)

    shape = functions.str_to_image_shape(sys.argv[1])
    app = ImageView(shape)
    app.run()
