#!/bin/bash

INFO=$'
Usage:

\timage_write H,W [ ... ImageMagick options ... ]
\timage_write H,W,3 [ ... ImageMagick options ... ]
'

case "$1" in
    *,*,*,*)
        echo "$INFO" 1>&2
        exit 1
    ;;
    *,*,3)
        SIZE="${1%,*}"
        SIZE="${SIZE##*,}x${SIZE%%,*}"
        FMT="RGB"
    ;;
    *,*,*)
        echo "$INFO" 1>&2
        exit 1
    ;;
    *,*)
        SIZE="${1##*,}x${1%%,*}"
        FMT="GRAY"
    ;;
    *)
        echo "$INFO" 1>&2
        exit 1
    ;;
esac

BYTES=$((${1//,/*})) || exit 1
shift

TMPDIR=$(mktemp -d) || exit 1
trap "rm -rf $TMPDIR" EXIT

SCENE=1
while dd bs=1 count=$BYTES of="$TMPDIR/chunk" status=none ; do
    READ_BYTES=$(stat -c%s "$TMPDIR/chunk")
    [ "x$READ_BYTES" = "x$BYTES" ] || exit 1
    convert \
        -size "$SIZE" -depth 8 "$FMT:$TMPDIR/chunk" \
        -scene "$SCENE" "$@" </dev/null || exit 1
    let SCENE=SCENE+1
done || exit 1

