#!/bin/bash

INFO=$'
Usage:

\timage_read H,W <file or directory>
\timage_read H,W,3 <file or directory>
'

if [ ! -e "$2" ]; then
    echo "$INFO" 1>&2
    exit 1
fi

case "$1" in
    *,*,*,*)
        echo "$INFO" 1>&2
        exit 1
    ;;
    *,*,3)
        OUT_FMT="${1%,*}"
        OUT_FMT="-resize ${OUT_FMT##*,}x${OUT_FMT%%,*}! -depth 8 RGB:-"
    ;;
    *,*,*)
        echo "$INFO" 1>&2
        exit 1
    ;;
    *,*)
        OUT_FMT="-resize ${1##*,}x${1%%,*}! -depth 8 GRAY:-"
    ;;
    *)
        echo "$INFO" 1>&2
        exit 1
    ;;
esac

if [ -d "$2" ]; then
    while IFS='' read -r f; do
        [ ! -d "$2/$f" ] || continue
        echo "Reading '$2/$f'..." 1>&2
        convert "$2/$f" $OUT_FMT || exit 1
    done <<<$(ls "$2") || exit 1
else
    echo "Reading '$2'..." 1>&2
    convert "$2" $OUT_FMT || exit 1
fi
