#!/usr/bin/env python3

import sys
import threading
import time
import numpy as np
import matplotlib.pyplot as plt

from utils import *

class ImageView():
    def __init__(self, shape):
        self.reader = read_arrays(sys.stdin.buffer, shape)

    def run(self):
        try:
            img = next(self.reader)
        except:
            return

        self.aximg = plt.imshow(img, vmin=0.0, vmax=1.0, cmap="gray")
        self.aximg.figure.canvas.draw()

        thread = threading.Thread(target = self.update_thread)
        thread.daemon = True
        thread.start()
        try:
            plt.show()
        except KeyboardInterrupt:
            pass

    def update_thread(self):
        try:
            for img in self.reader:
                self.aximg.set_data(img)
                self.aximg.figure.canvas.draw()
        except:
            return

def run():
    if len(sys.argv) < 2:
        sys.stderr.write("\nUsage:\n\n");
        sys.stderr.write("\timage_show H,W\n")
        sys.stderr.write("\timage_show H,W,3\n\n")
        sys.exit(1)

    shape = str_to_image_shape(sys.argv[1])
    app = ImageView(shape)
    app.run()

if __name__ == "__main__":
    run()
