#!/usr/bin/env python3

import sys
import numpy as np

import loadsave
from utils import *

def process_stdin(sess, x, y):
    for x_val in read_arrays(sys.stdin.buffer, x.shape.as_list()):
        y_val = sess.run(y, feed_dict = {x: x_val})
        write_array(sys.stdout.buffer, y_val)

def run():
    if len(sys.argv) < 4:
        sys.stderr.write("\nUsage:\n\n");
        sys.stderr.write("\tmodel_run <dir.model> <input tensor> <output tensor>\n\n")
        sys.exit(1)

    if sys.stdout.isatty():
        sys.stderr.write("Error: Refusing to write binary data to a terminal\n")
        sys.exit(1)

    with loadsave.load(sys.argv[1]) as sess:
        x = sess.graph.get_tensor_by_name(sys.argv[2])
        y = sess.graph.get_tensor_by_name(sys.argv[3])
        process_stdin(sess, x, y)

if __name__ == "__main__":
    run()
